import { useState, useEffect, useRef } from "react";

const FONTS = `@import url('https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300;1,9..40,400&family=Playfair+Display:ital,wght@0,700;0,900;1,400;1,700&display=swap');`;

// ─── PALETTE — warm, cream, human ───────────────────────────────────────────
const C = {
  cream:    "#F5F0E8",
  warmwht:  "#FAF8F4",
  parchmt:  "#EDE8DC",
  gold:     "#B8860B",
  goldlt:   "#D4A843",
  goldwarm: "#C9A84C",
  earth:    "#6B5B3E",
  darkearth:"#3D3428",
  mid:      "#8A7B6A",
  soft:     "#B5A898",
  sage:     "#7A8C6E",
  rose:     "#C17B6A",
  ink:      "#1E1A14",
  olive:    "#6B7355",
};

// ─── THE FAIR TRADE STANDARD ────────────────────────────────────────────────
const STANDARDS = [
  {
    num: "I",
    title: "Consent Before Creation",
    principle: "No artist's voice, music, or creative work is used to train AI models without their explicit, informed, revocable consent — and a fair compensation agreement signed before training begins.",
    what_it_means: "Asking permission is not a legal formality. It is the first act of respect. Every platform that trains on human creativity owes that human a conversation before a single byte is processed.",
    icon: "◯",
    color: C.sage,
  },
  {
    num: "II",
    title: "Artists Own What They Make",
    principle: "Every work created using Fair Trade certified tools belongs to the artist who created it from the moment of creation. Platforms may host. Platforms may distribute. Platforms do not own.",
    what_it_means: "A hammer does not own the house. A canvas does not own the painting. A platform does not own the music made inside it. Ownership flows to the human who made the creative decision.",
    icon: "◈",
    color: C.goldwarm,
  },
  {
    num: "III",
    title: "Revenue Routes to Creators First",
    principle: "A minimum of 70% of all commercial revenue generated by an artist's work, voice, or likeness routes to that artist — automatically, transparently, in real currency.",
    what_it_means: "Not credits. Not exposure. Not a share of a pool nobody can audit. Real money, to the real human, in the first routing — not what's left after the platform takes its share.",
    icon: "◆",
    color: C.goldlt,
  },
  {
    num: "IV",
    title: "Intelligence Belongs to Its Source",
    principle: "Analytics generated about an artist's work — spectral fingerprints, style profiles, commercial placement data, audience intelligence — belong to that artist and are provided to them in full.",
    what_it_means: "When a platform uses your creativity to make itself smarter, it owes you that intelligence in return. Knowing what your sound IS, commercially and artistically, is not a premium feature. It is your right.",
    icon: "◎",
    color: C.rose,
  },
  {
    num: "V",
    title: "Training Data Has Provenance",
    principle: "Every AI model certified under the Fair Trade Standard publishes a complete, auditable account of what music, voice, and creative work trained it — including how each contributor was credited and compensated.",
    what_it_means: "The question 'what was this trained on' must have a public, verifiable answer. An AI that cannot account for its own training data carries a moral debt that compounds with every output it generates.",
    icon: "⬡",
    color: C.earth,
  },
  {
    num: "VI",
    title: "Portability Is a Right",
    principle: "Artists can export their full history — every creation, every earning record, every signal profile — and take it anywhere. Platforms that trap artists in subscription dependency through data lock-in are not certified.",
    what_it_means: "You should be able to leave. Any platform that makes leaving impossible has chosen dependency over partnership. Fair Trade means the relationship is voluntary at every moment.",
    icon: "→",
    color: C.olive,
  },
  {
    num: "VII",
    title: "Community Builds Equity",
    principle: "The artists and creators who build a platform's library, community, and creative culture participate in the financial value that culture creates — through transparent profit sharing, equity participation, or community funds.",
    what_it_means: "The people who build the thing that makes the platform valuable are not suppliers. They are founders. Treating them as vendors is the original sin of the creator economy.",
    icon: "◉",
    color: C.sage,
  },
  {
    num: "VIII",
    title: "Emerging Voices Have Equal Access",
    principle: "Discovery systems, feature access, and opportunity are not gated by established reputation or engagement history. A voice with three recordings deserves the same algorithmic consideration as a voice with three thousand.",
    what_it_means: "The most important voice in the next decade might be someone who made their first recording last Tuesday. Fair Trade platforms build for that person, not just for the established.",
    icon: "↑",
    color: C.goldwarm,
  },
];

// ─── THE INVITATION TO PLATFORMS ────────────────────────────────────────────
const PLATFORM_PATH = [
  {
    step: "01",
    title: "Self-Assessment",
    desc: "Any platform may request a Fair Trade audit. The audit reviews training data provenance, revenue routing, consent architecture, and artist exit rights. Assessment is free. Honesty is required.",
    time: "2-4 weeks",
  },
  {
    step: "02",
    title: "Gap Analysis",
    desc: "The audit produces a plain-language Gap Report — what meets the standard, what doesn't, and specifically what changes are required. No shame. No public disclosure at this stage. Just clarity.",
    time: "1-2 weeks",
  },
  {
    step: "03",
    title: "The Pathway",
    desc: "Platforms that want to certify receive a 12-month implementation pathway with NOIZY.ai's technical team available to consult on consent architecture, royalty routing, and data portability implementation.",
    time: "Up to 12 months",
  },
  {
    step: "04",
    title: "Certification",
    desc: "Platforms that meet all eight standards receive Fair Trade AI Audio certification — a mark that tells artists, studios, and buyers: this platform treats creators fairly. Renewed annually.",
    time: "Annual review",
  },
];

// ─── WHO THIS IS FOR ─────────────────────────────────────────────────────────
const VOICES = [
  {
    role: "Voice Actors",
    worry: "My voice might already be in a training model I didn't consent to. My career is 20 years of craft. I don't know if it still has value.",
    hope: "Fair Trade certification means the tools I use have made a legal and ethical commitment to me before I ever upload a single file. I know where I stand.",
    initials: "VA", color: C.goldwarm,
  },
  {
    role: "Composers",
    worry: "Suno generated a song last week that sounds like me. I can't prove it. There's no recourse. No one I can call.",
    hope: "A Fair Trade certified music platform traces its training data. If my music trained the model, I was asked first, and I was paid. If it didn't, the platform can prove it.",
    initials: "CP", color: C.sage,
  },
  {
    role: "Sound Designers",
    worry: "I've uploaded thousands of samples to marketplaces over 15 years. They were licensed once for flat fees. I have no idea how many times they've been used since.",
    hope: "Fair Trade means usage-based royalties — not flat buyouts. My catalog earns as long as it's used. My work has a permanent economic relationship with the world.",
    initials: "SD", color: C.rose,
  },
  {
    role: "AI Platform Builders",
    worry: "The legal landscape is chaos. We built something real, but we're not sure our training data sourcing survives a serious legal challenge. We want to do this right.",
    hope: "Fair Trade certification is also protection for us. Documented consent, clean provenance, transparent attribution — this is how we build something that lasts.",
    initials: "PB", color: C.olive,
  },
  {
    role: "Emerging Artists",
    worry: "I graduated two years ago. I've never known a market without AI. I don't know if my voice has value or if I'm already obsolete before I started.",
    hope: "Fair Trade platforms evaluate voices by signal intelligence, not engagement history. My first recording gets the same algorithmic shot as anyone's. The field is level.",
    initials: "EA", color: C.earth,
  },
  {
    role: "Music Supervisors",
    worry: "I want to use AI tools to find music faster. But I'm terrified of licensing liability. If a track I placed was trained on unlicensed material, that's on me.",
    hope: "Fair Trade certified tools come with clean provenance documentation. Every track I source has a documented training lineage. My legal exposure drops to zero.",
    initials: "MS", color: C.goldlt,
  },
];

// ─── WHAT FAIR TRADE LOOKS LIKE ──────────────────────────────────────────────
const EXAMPLES = [
  {
    scenario: "A gaming studio wants AI voice for 200 NPC characters",
    without: "Studio uses ElevenLabs API. Voices generated from models trained on unattributed voice actor recordings. No consent obtained. No royalties paid. Voice actors whose work trained the model: $0.",
    with: "Studio uses NOIZY Guild via Fair Trade certified API. Each voice model is consent-locked. Studio's request is checked against each model's permitted categories. 75% of the invoice routes to 4 Guild voice artists. Voice actors: paid for every use, forever.",
    saved: "$0 vs $2,400 to artists",
  },
  {
    scenario: "A songwriter uses AI to generate a demo backing track",
    without: "Songwriter uses Suno. Demo is generated from a model trained on scraped recordings. Songwriter owns the demo but has no intelligence about what makes it work, what genre it sits in, or where it might be placed commercially.",
    with: "Songwriter uses NOIZY DreamChamber. Demo is generated from licensed training data. GABRIEL provides full signal intelligence report: genre, mood, commercial placement categories, sync brief matches. Songwriter knows what they have.",
    saved: "Zero intelligence vs full creative brief",
  },
  {
    scenario: "A producer uploads 50 original samples to a marketplace",
    without: "Producer uploads to Splice. Accepts royalty-free perpetual license for $1.50 per accepted sample. Total one-time payment: $75. Those 50 samples: accessed by 4M+ subscribers indefinitely. Producer: never paid again.",
    with: "Producer uploads to NOIZY Sample Marketplace. Usage-based royalties. Each download: $0.008. Each commercial placement: 3% of sync fee. After 12 months with 500 downloads: $4 in download royalties + $180 in sync placement royalties. Producer: $184 vs $75, and it compounds.",
    saved: "$75 one-time vs $184+ and growing",
  },
];

// ─── HARMONY DATA ───────────────────────────────────────────────────────────
const HARMONY_PILLARS = [
  {
    title:"The Composer Who Found Their Voice",
    body:"A film composer uses GABRIEL's emotional signature analysis to map the arc of their ten-year catalog. They discover their most-licensed work clusters around a specific tension-to-release ratio they hadn't consciously noticed. They write their next score with that knowledge made explicit — and it is the best work of their career.",
    icon:"◬", color:C.goldwarm,
  },
  {
    title:"The Voice Actor Who Multiplied Themselves",
    body:"A voice actor licenses their performance range to a Fair Trade certified synthesis platform through NOIZY Guild. Their voice appears in 40 audiobooks in a single year — works they could never have recorded in that time. The royalties fund the studio upgrade they'd been delaying. They still record everything they want to record in person.",
    icon:"◈", color:C.sage,
  },
  {
    title:"The Sound Designer Who Built a Living Library",
    body:"A sound designer uploads 2,000 recordings to the NOIZY Sample Marketplace. GABRIEL identifies harmonic relationships between samples that the designer hadn't noticed. Licensees begin requesting combinations that become a signature collection. The AI found the pattern; the human made it meaningful.",
    icon:"◎", color:C.rose,
  },
  {
    title:"The Band That Trained Their Own Model",
    body:"An independent band uses their consented catalog to fine-tune a GABRIEL model that understands their specific sonic language. They use it to generate reference arrangements when writing new material — not finished songs, but mirrors that show them what they're trying to say. The songs that come out are unmistakably theirs.",
    icon:"◉", color:C.earth,
  },
];

const FLYWHEEL_STEPS = [
  { label:"Consent-Based Training", desc:"Artists opt in with full transparency about how their work will be used, what models it will train, and what compensation applies. The foundation is clean." },
  { label:"Richer, More Ethical AI Models", desc:"Models trained on consented, documented, culturally diverse work are more nuanced and carry no legal or ethical debt. The output is better because the input was honest." },
  { label:"Better Tools for Artists", desc:"Richer models power tools that genuinely serve creative work — intelligent arrangement assistants, emotional signature analysis, genre-evolution mapping. The tools become worth using." },
  { label:"More Artists Participate", desc:"When artists see real value returning to them — in compensation, capability, recognition — more choose to participate. The pool of contributing creators grows organically." },
  { label:"The Model Deepens Again", desc:"A larger, more diverse, more willing contributor base feeds the next training cycle. Each revolution of the flywheel makes the next one more powerful." },
];

// ─── ECOSYSTEM DATA ──────────────────────────────────────────────────────────
const ECOSYSTEM_NODES = [
  { role:"Independent Artists", gives:"Creative work, voice performances, original compositions — the raw material of the entire economy", receives:"Consent-based compensation, attribution in AI lineage, tools that amplify their output, a standard that protects their future work", color:C.gold, initials:"IA" },
  { role:"Voice Actors", gives:"Vocal performances that train synthesis models, emotional range data, character voice libraries", receives:"Royalties on model usage, NOIZY Guild protections, certification that their voice cannot be used without ongoing consent", color:C.rose, initials:"VA" },
  { role:"Music Supervisors", gives:"Licensing demand signals, placement context, real-world use case data that sharpens AI relevance", receives:"Curated catalogs they can license with confidence, Fair Trade certification that eliminates liability risk", color:C.sage, initials:"MS" },
  { role:"AI Developers", gives:"Technical infrastructure, model architecture, deployment capability, compute resources", receives:"Ethically sourced training data, regulatory goodwill, trust signals from creators who would otherwise refuse", color:C.earth, initials:"AD" },
  { role:"Brands & Advertisers", gives:"Budgets, production demand, distribution reach that exposes Fair Trade work to mass audiences", receives:"Cleared, licensed AI-assisted audio production without reputational risk — a supply chain their legal team can describe without hesitation", color:C.olive, initials:"BA" },
  { role:"Independent Platforms", gives:"Distribution infrastructure, artist communities, listener data that contextualizes creative value", receives:"Fair Trade certification as a competitive differentiator, tools their artists actually want, a shared standard that levels the field", color:C.mid, initials:"IP" },
];

const NOIZY_PRODUCTS = [
  { name:"NOIZY Guild", tagline:"The voice actor's first line of defense in the AI era", serves:"Voice actors who need consent management, royalty tracking, and protection against unauthorized synthesis", color:C.rose },
  { name:"NOIZY DreamChamber", tagline:"Where composers and producers find what their music is trying to become", serves:"Composers and producers using GABRIEL's emotional signature intelligence to understand and consciously evolve their creative voice", color:C.gold },
  { name:"NOIZY Sample Marketplace", tagline:"Every sound carries a clear chain of title", serves:"Sound designers who want their work licensed transparently, attributed accurately, and compensated automatically", color:C.sage },
  { name:"GABRIEL Intelligence", tagline:"The signal layer that connects creative intent to creative output", serves:"All creators — the underlying AI intelligence trained exclusively on consented work, powering every Fair Trade tool", color:C.earth },
  { name:"NOIZY API", tagline:"Fair Trade infrastructure, available to every platform that chooses it", serves:"Developers and platforms who want to build ethical AI audio features without building the ethics layer themselves", color:C.olive },
];

const GROWTH_PHASES = [
  { phase:"Seed", title:"0 – 100 Certified Platforms", desc:"Early certifiers are pioneers who accept that the value of being first is real but invisible. They establish the vocabulary, the audit process, the precedent. This is the phase where credibility is built by people who didn't need to wait for it to be credible.", milestone:"First independent platform certifies. First artist receives a consent-based AI training royalty. The infrastructure exists." },
  { phase:"Growth", title:"100 – 1,000 Certified Platforms", desc:"Network effects begin to compound. A music supervisor discovers that every Fair Trade certified platform surfaces pre-cleared work and changes their workflow. An AI developer discovers that certification speeds their enterprise sales cycle. The standard becomes a business argument, not just an ethical one.", milestone:"A major DAW integrates Fair Trade metadata. The first legal brief cites the standard. Industry press covers certification as a competitive signal." },
  { phase:"Abundance", title:"1,000+ Certified Platforms", desc:"The standard is infrastructure. New platforms launch Fair Trade certified from day one because any other posture is a liability. Creators default to consented training contracts because the legal architecture makes non-consent the harder path.", milestone:"The first country legislates consent requirements that mirror this standard. Fair Trade AI Audio is the default expectation, not the premium option." },
];

// ─── VISION DATA ─────────────────────────────────────────────────────────────
const VISION_TIMELINE = [
  { year:"2026", title:"NOIZY Self-Certifies", desc:"We don't ask others to meet a standard we haven't met ourselves. NOIZY.ai becomes the first platform to complete full Fair Trade AI Audio certification against its own published standard. Every GABRIEL training dataset is audited and documented. Every artist in our system has an active consent record.", status:"done" },
  { year:"2027", title:"The First Ten", desc:"Ten independent platforms complete certification across different genres, geographies, and sizes. The standard proves it can work for a voice acting platform in Nashville, an electronic music community in Berlin, and an ambient sound library in São Paulo. Universality is tested, not assumed.", status:"near" },
  { year:"2028", title:"A Major DAW Integrates", desc:"The first major digital audio workstation ships a Fair Trade metadata layer — the ability to flag recordings as consent-certified at the moment of creation. An artist recording a vocal in Logic or Ableton can, in the same session, establish their AI training permissions.", status:"near" },
  { year:"2030", title:"The First Legislation", desc:"A country — likely in the EU or Scandinavia — passes consent requirements for AI audio training that explicitly cite the Fair Trade AI Audio standard as the compliance pathway. The standard transitions from industry voluntary to legislative reference.", status:"horizon" },
  { year:"2035", title:"The Default Expectation", desc:"Fair Trade AI Audio certification is no longer a differentiator — it is the baseline. New AI audio companies launch certified because launching any other way makes fundraising harder, partnerships slower, and artist trust impossible. The coffee analogy completes itself.", status:"horizon" },
];

const LETTERS = [
  { to:"A voice actor in 2035", year:"2035", body:"You grew up knowing your voice was yours. Not in a sentimental way — in a legal, financial, and technical way. When a brand wanted to use a synthetic version of your vocal style, there was a contract. When a model was trained on your performances, there was a record and a royalty. You didn't have to fight for this; it was already the architecture of the industry when you entered it. We built that architecture in 2026 because we knew you were coming, and we wanted the world to be ready for you." },
  { to:"A music supervisor in 2030", year:"2030", body:"You remember what it was like before — running a cue list through legal and waiting three weeks to find out if an AI-generated underscore had a consent problem buried in its training data. Now you pull a Fair Trade certified catalog and place it the same day. The trust is structural, not assumed. You're doing more creative work and less defensive work. That was always the point." },
  { to:"An AI developer in 2028", year:"2028", body:"You built your platform on Fair Trade infrastructure from the first line of code. Your competitors thought that was a constraint. You found it was a moat. Enterprise clients closed faster because your legal team had answers. Artist communities chose your platform because you had a language they recognized. The ethics layer turned out to be the business layer. You didn't compromise on principles to build something real — you built something real because you didn't compromise on principles." },
];

// ─── COMPONENTS ──────────────────────────────────────────────────────────────

const StandardCard = ({ standard, idx }) => {
  const [hover, setHover] = useState(false);
  return (
    <div
      onMouseEnter={()=>setHover(true)}
      onMouseLeave={()=>setHover(false)}
      style={{
        padding:"28px 28px 24px",
        background: hover ? C.warmwht : C.cream,
        border:`1px solid ${hover?standard.color+"44":C.parchmt}`,
        borderTop:`3px solid ${standard.color}`,
        borderRadius:4,
        transition:"all 0.25s ease",
        animation:`rise 0.5s ease ${idx*0.06}s both`,
      }}
    >
      <div style={{
        display:"flex", alignItems:"flex-start",
        justifyContent:"space-between", marginBottom:16,
      }}>
        <div style={{
          fontFamily:"Playfair Display", fontSize:11,
          fontWeight:700, color:standard.color,
          letterSpacing:3, textTransform:"uppercase",
        }}>Standard {standard.num}</div>
        <div style={{
          fontSize:22, color:standard.color, opacity:0.4,
        }}>{standard.icon}</div>
      </div>
      <div style={{
        fontFamily:"Playfair Display", fontSize:17,
        fontWeight:700, color:C.ink, lineHeight:1.3,
        marginBottom:12,
      }}>{standard.title}</div>
      <div style={{
        fontFamily:"Lora", fontSize:12, color:C.earth,
        lineHeight:1.8, marginBottom:14,
        fontStyle:"italic",
      }}>"{standard.principle}"</div>
      <div style={{
        height:1, background:C.parchmt, marginBottom:14,
      }}/>
      <div style={{
        fontFamily:"DM Sans", fontSize:12, color:C.mid,
        lineHeight:1.7,
      }}>{standard.what_it_means}</div>
    </div>
  );
};

const VoiceCard = ({ voice }) => (
  <div style={{
    background:C.cream, border:`1px solid ${C.parchmt}`,
    borderRadius:4, overflow:"hidden",
  }}>
    <div style={{
      padding:"20px 24px 16px",
      background: `linear-gradient(135deg, ${voice.color}14, ${voice.color}06)`,
      borderBottom:`1px solid ${C.parchmt}`,
    }}>
      <div style={{display:"flex", gap:14, alignItems:"center", marginBottom:12}}>
        <div style={{
          width:44, height:44, borderRadius:"50%",
          background:`${voice.color}20`,
          border:`2px solid ${voice.color}`,
          display:"flex", alignItems:"center", justifyContent:"center",
          fontFamily:"Playfair Display", fontSize:13, fontWeight:700,
          color:voice.color, flexShrink:0,
        }}>{voice.initials}</div>
        <div style={{
          fontFamily:"Lora", fontSize:15, fontWeight:700,
          color:C.ink,
        }}>{voice.role}</div>
      </div>
      <div style={{
        fontFamily:"DM Sans", fontSize:12, color:C.mid,
        lineHeight:1.7, fontStyle:"italic",
      }}>"{voice.worry}"</div>
    </div>
    <div style={{padding:"16px 24px 20px"}}>
      <div style={{
        fontFamily:"DM Sans", fontSize:11, fontWeight:500,
        color:voice.color, letterSpacing:2, marginBottom:8,
        textTransform:"uppercase",
      }}>What Fair Trade gives them</div>
      <div style={{
        fontFamily:"DM Sans", fontSize:12, color:C.earth,
        lineHeight:1.7,
      }}>{voice.hope}</div>
    </div>
  </div>
);

const PathStep = ({ step }) => (
  <div style={{
    padding:"24px 28px",
    background:C.cream, border:`1px solid ${C.parchmt}`,
    borderRadius:4, position:"relative",
  }}>
    <div style={{
      fontFamily:"Playfair Display", fontSize:48, fontWeight:900,
      color:C.parchmt, position:"absolute", top:12, right:20,
      lineHeight:1, userSelect:"none",
    }}>{step.step}</div>
    <div style={{
      fontFamily:"DM Sans", fontSize:11, fontWeight:500,
      color:C.goldwarm, letterSpacing:2, marginBottom:8,
      textTransform:"uppercase",
    }}>Step {step.step}</div>
    <div style={{
      fontFamily:"Lora", fontSize:16, fontWeight:700,
      color:C.ink, marginBottom:10,
    }}>{step.title}</div>
    <div style={{
      fontFamily:"DM Sans", fontSize:12, color:C.mid, lineHeight:1.7,
      marginBottom:12,
    }}>{step.desc}</div>
    <div style={{
      fontFamily:"DM Sans", fontSize:10, color:C.soft,
      letterSpacing:1, textTransform:"uppercase",
    }}>{step.time}</div>
  </div>
);

const ExampleCard = ({ ex, idx }) => (
  <div style={{
    background:C.warmwht, border:`1px solid ${C.parchmt}`,
    borderRadius:4, overflow:"hidden", marginBottom:16,
  }}>
    <div style={{
      padding:"16px 24px",
      background:C.cream,
      borderBottom:`1px solid ${C.parchmt}`,
    }}>
      <div style={{
        fontFamily:"DM Sans", fontSize:10, fontWeight:500,
        color:C.goldwarm, letterSpacing:2, marginBottom:4,
        textTransform:"uppercase",
      }}>Real Scenario {idx+1}</div>
      <div style={{fontFamily:"Lora", fontSize:15, fontWeight:700, color:C.ink}}>
        {ex.scenario}
      </div>
    </div>
    <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:0}}>
      <div style={{padding:"20px 24px", borderRight:`1px solid ${C.parchmt}`}}>
        <div style={{
          fontFamily:"DM Sans", fontSize:10, fontWeight:500,
          color:"#C17B6A", letterSpacing:2, marginBottom:10,
          textTransform:"uppercase",
        }}>Without Fair Trade</div>
        <div style={{fontFamily:"DM Sans", fontSize:12, color:C.mid, lineHeight:1.7}}>{ex.without}</div>
      </div>
      <div style={{padding:"20px 24px"}}>
        <div style={{
          fontFamily:"DM Sans", fontSize:10, fontWeight:500,
          color:C.sage, letterSpacing:2, marginBottom:10,
          textTransform:"uppercase",
        }}>With Fair Trade</div>
        <div style={{fontFamily:"DM Sans", fontSize:12, color:C.earth, lineHeight:1.7}}>{ex.with}</div>
      </div>
    </div>
    <div style={{
      padding:"12px 24px",
      background:`${C.goldwarm}0F`,
      borderTop:`1px solid ${C.parchmt}`,
      display:"flex", justifyContent:"space-between", alignItems:"center",
    }}>
      <span style={{fontFamily:"DM Sans", fontSize:10, color:C.soft, letterSpacing:1, textTransform:"uppercase"}}>Difference to Artist</span>
      <span style={{fontFamily:"Lora", fontSize:14, fontWeight:700, color:C.goldwarm}}>{ex.saved}</span>
    </div>
  </div>
);

// ─── CERTIFICATION BADGE ─────────────────────────────────────────────────────
const CertBadge = ({ size=80 }) => (
  <svg width={size} height={size} viewBox="0 0 80 80">
    <circle cx="40" cy="40" r="38" fill="none" stroke={C.goldwarm} strokeWidth="2"/>
    <circle cx="40" cy="40" r="32" fill={`${C.goldwarm}15`}/>
    {[...Array(8)].map((_,i)=>{
      const a=(i/8)*Math.PI*2-Math.PI/2;
      return <line key={i} x1={40+31*Math.cos(a)} y1={40+31*Math.sin(a)} x2={40+35*Math.cos(a)} y2={40+35*Math.sin(a)} stroke={C.goldwarm} strokeWidth="1.5"/>;
    })}
    <text x="40" y="36" textAnchor="middle" fontFamily="Playfair Display" fontSize="7" fill={C.goldwarm} fontWeight="700">FAIR TRADE</text>
    <text x="40" y="47" textAnchor="middle" fontFamily="Playfair Display" fontSize="9" fill={C.goldwarm} fontWeight="900" fontStyle="italic">AI Audio</text>
    <text x="40" y="57" textAnchor="middle" fontFamily="DM Sans" fontSize="5" fill={C.mid} letterSpacing="1">CERTIFIED</text>
  </svg>
);

// ─── LIVE PLEDGE COUNTER ──────────────────────────────────────────────────────
const usePledgeCounter = () => {
  const [count, setCount] = useState(847);
  useEffect(()=>{
    const id = setInterval(()=>{
      if(Math.random()<0.15) setCount(c=>c+1);
    }, 6000);
    return ()=>clearInterval(id);
  },[]);
  return count;
};

// ─── MAIN ────────────────────────────────────────────────────────────────────
export default function FairTradeAI() {
  const [view, setView] = useState("about");
  const [pledged, setPledged] = useState(false);
  const [signName, setSignName] = useState("");
  const [signRole, setSignRole] = useState("");
  const [signed, setSigned] = useState(false);
  const pledgeCount = usePledgeCounter();
  const [activeStandard, setActiveStandard] = useState(null);

  const handleSign = () => {
    if(signName.trim()) { setSigned(true); setPledged(true); }
  };

  return (
    <div style={{
      background:C.warmwht, color:C.ink,
      minHeight:"100vh", fontFamily:"DM Sans, sans-serif",
    }}>
      <style>{FONTS}{`
        @keyframes rise{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
        @keyframes fadeIn{from{opacity:0}to{opacity:1}}
        @keyframes breathe{0%,100%{transform:scale(1)}50%{transform:scale(1.02)}}
        *{box-sizing:border-box;margin:0;padding:0}
        ::-webkit-scrollbar{width:4px}
        ::-webkit-scrollbar-thumb{background:${C.parchmt}}
        button{cursor:pointer}
        input,textarea{outline:none}
        .soft-hover:hover{background:${C.cream}!important;transition:background 0.2s}
      `}</style>

      {/* ── HEADER ──────────────────────────────────────── */}
      <div style={{
        padding:"20px 40px",
        background:C.cream,
        borderBottom:`1px solid ${C.parchmt}`,
        display:"flex", alignItems:"center",
        justifyContent:"space-between",
        position:"sticky", top:0, zIndex:100,
      }}>
        <div style={{display:"flex", alignItems:"center", gap:16}}>
          <CertBadge size={48}/>
          <div>
            <div style={{
              fontFamily:"Playfair Display", fontSize:18, fontWeight:900,
              color:C.ink, letterSpacing:0.5,
            }}>Fair Trade AI Audio</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:10, color:C.mid,
              letterSpacing:2, textTransform:"uppercase", marginTop:1,
            }}>A Standard for Human-Centred Creative AI</div>
          </div>
        </div>
        <div style={{display:"flex", alignItems:"center", gap:8}}>
          <div style={{
            display:"flex", alignItems:"center", gap:8,
            padding:"8px 16px",
            background:C.warmwht, border:`1px solid ${C.parchmt}`,
            borderRadius:20,
          }}>
            <div style={{
              width:7, height:7, borderRadius:"50%",
              background:C.sage,
              boxShadow:`0 0 6px ${C.sage}88`,
            }}/>
            <span style={{fontFamily:"DM Sans", fontSize:11, color:C.mid}}>
              {pledgeCount.toLocaleString()} signatories
            </span>
          </div>
          <div style={{
            fontFamily:"Lora", fontSize:12, fontStyle:"italic",
            color:C.goldwarm, padding:"8px 16px",
          }}>by NOIZY.ai</div>
        </div>
      </div>

      {/* ── HERO ──────────────────────────────────────────── */}
      <div style={{
        padding:"80px 40px 72px",
        background:`linear-gradient(180deg, ${C.cream} 0%, ${C.warmwht} 100%)`,
        borderBottom:`1px solid ${C.parchmt}`,
        position:"relative", overflow:"hidden",
      }}>
        {/* Decorative rings */}
        {[200,320,440].map((r,i)=>(
          <div key={i} style={{
            position:"absolute", top:"50%", right:"-10%",
            width:r, height:r, borderRadius:"50%",
            border:`1px solid ${C.goldwarm}${12+i*8}`,
            transform:"translate(0,-50%)",
            pointerEvents:"none",
            animation:`breathe ${3+i}s ease infinite`,
          }}/>
        ))}

        <div style={{maxWidth:780, position:"relative"}}>
          <div style={{
            fontFamily:"DM Sans", fontSize:10, fontWeight:500,
            color:C.goldwarm, letterSpacing:4, textTransform:"uppercase",
            marginBottom:20,
          }}>A Message From NOIZY.ai Founder Rob Plowman</div>

          <div style={{
            fontFamily:"Playfair Display", fontSize:48, fontWeight:700,
            fontStyle:"italic", lineHeight:1.15, color:C.ink,
            marginBottom:28,
          }}>
            "I have nothing against anyone.<br/>
            I just want to preserve artists —<br/>
            <span style={{color:C.goldwarm}}>and fair trade for all."</span>
          </div>

          <div style={{
            fontFamily:"Lora", fontSize:16, color:C.earth,
            lineHeight:1.8, maxWidth:640, marginBottom:36,
          }}>
            This is not a war against technology companies. It is an invitation to them.
            Fair Trade did not destroy the coffee industry — it made it better.
            Better for farmers. Better for buyers. Better for everyone in the chain
            who ever cared about where the thing came from and whether the person
            who made it was treated with dignity.
            <br/><br/>
            We are extending that same invitation to every AI audio platform in the world.
            Come and be certified. The standard is clear. The pathway is open.
            The artists are waiting.
          </div>

          <div style={{
            display:"flex", gap:12, flexWrap:"wrap",
          }}>
            {["Voice Actors","Composers","Sound Designers","AI Platforms","Music Studios","Sync Agencies","Producers","Developers"].map(tag=>(
              <span key={tag} style={{
                padding:"6px 14px", borderRadius:20,
                border:`1px solid ${C.parchmt}`,
                background:C.cream,
                fontFamily:"DM Sans", fontSize:11, color:C.mid,
              }}>{tag}</span>
            ))}
          </div>
        </div>
      </div>

      {/* ── NAV ───────────────────────────────────────────── */}
      <div style={{
        display:"flex", borderBottom:`1px solid ${C.parchmt}`,
        background:C.cream, position:"sticky", top:68, zIndex:99,
        padding:"0 40px",
      }}>
        {[
          {id:"about",  label:"About This Standard"},
          {id:"standards", label:"The Eight Standards"},
          {id:"voices", label:"Who This Serves"},
          {id:"path",   label:"Path to Certification"},
          {id:"examples", label:"What It Looks Like"},
          {id:"pledge", label:"Sign the Pledge"},
          {id:"harmony", label:"AI & Human Harmony"},
          {id:"ecosystem", label:"The NOIZY Ecosystem"},
          {id:"vision", label:"The Vision"},
        ].map(t=>(
          <button key={t.id} onClick={()=>setView(t.id)} style={{
            padding:"14px 18px",
            background:"transparent",
            border:"none",
            borderBottom:`2px solid ${view===t.id?C.goldwarm:"transparent"}`,
            color:view===t.id?C.goldwarm:C.mid,
            fontFamily:"DM Sans", fontSize:11, fontWeight:view===t.id?500:400,
            letterSpacing:0.5, transition:"all 0.15s", whiteSpace:"nowrap",
          }}>{t.label}</button>
        ))}
      </div>

      {/* ── CONTENT ───────────────────────────────────────── */}
      <div style={{padding:"44px 40px 80px", maxWidth:1300, margin:"0 auto"}}>

        {/* ABOUT */}
        {view==="about" && (
          <div style={{maxWidth:860, animation:"rise 0.4s ease"}}>
            <div style={{
              fontFamily:"Playfair Display", fontSize:38, fontWeight:700,
              color:C.ink, marginBottom:8, lineHeight:1.2,
            }}>What Is Fair Trade AI Audio?</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:11, color:C.soft,
              letterSpacing:3, textTransform:"uppercase", marginBottom:36,
            }}>An open standard. A voluntary certification. An invitation.</div>

            <div style={{
              display:"grid", gridTemplateColumns:"1fr 1fr", gap:24, marginBottom:40,
            }}>
              {[
                {
                  title:"What It Is",
                  body:"Fair Trade AI Audio is a voluntary certification standard for AI platforms that use human creative work — voice, music, samples, sound design — as training data, content, or creative input. It establishes minimum standards for consent, compensation, attribution, and artist rights.",
                  icon:"◯",
                },
                {
                  title:"What It Is Not",
                  body:"Fair Trade AI Audio is not an anti-technology movement. It is not a lawsuit. It is not a boycott. It is not an attempt to stop the development of AI. It is an attempt to ensure that the development of AI includes the humans whose creativity makes it possible.",
                  icon:"◈",
                },
                {
                  title:"Who Created It",
                  body:"Rob Plowman — composer, voice actor, sound designer, and founder of NOIZY.ai — created this standard because he is both an artist who needed it and a technologist who could build it. NOIZY.ai is the first platform to self-certify under this standard.",
                  icon:"◆",
                },
                {
                  title:"How It Works",
                  body:"Eight standards. A public audit pathway. Annual renewal. Any platform — from a two-person startup to a major technology company — can apply for certification. The standards are the same for everyone. The timeline is generous. The invitation is genuine.",
                  icon:"◉",
                },
              ].map((c,i)=>(
                <div key={i} style={{
                  padding:"24px 28px",
                  background:C.cream, border:`1px solid ${C.parchmt}`,
                  borderRadius:4, animation:`rise 0.4s ease ${i*0.08}s both`,
                }}>
                  <div style={{
                    fontFamily:"Playfair Display", fontSize:16, fontWeight:700,
                    color:C.ink, marginBottom:10,
                  }}>{c.title}</div>
                  <div style={{
                    fontFamily:"DM Sans", fontSize:13, color:C.mid, lineHeight:1.7,
                  }}>{c.body}</div>
                </div>
              ))}
            </div>

            {/* The Fair Trade parallel */}
            <div style={{
              padding:"32px 36px",
              background:C.cream,
              border:`1px solid ${C.parchmt}`,
              borderLeft:`4px solid ${C.goldwarm}`,
              borderRadius:4, marginBottom:32,
            }}>
              <div style={{
                fontFamily:"Playfair Display", fontSize:18, fontWeight:700,
                color:C.ink, marginBottom:16,
              }}>Why Fair Trade?</div>
              <div style={{
                fontFamily:"Lora", fontSize:14, color:C.earth,
                lineHeight:1.9, fontStyle:"italic", marginBottom:16,
              }}>
                "In 1988, the first Fair Trade label appeared on coffee bags in the Netherlands.
                It did not destroy the coffee industry. It gave conscious buyers a way to choose,
                gave ethical producers a competitive signal, and gave farmers a guarantee.
                Within twenty years, Fair Trade coffee was in every major supermarket in the world.
                The industry improved — not because companies were forced, but because the standard
                showed a better way was possible."
              </div>
              <div style={{
                fontFamily:"DM Sans", fontSize:13, color:C.mid, lineHeight:1.7,
              }}>
                Fair Trade AI Audio is the same invitation. We are not asking AI companies to stop.
                We are showing them a better way. We are giving artists a label they can trust.
                We are giving buyers — studios, brands, platforms, sync agencies — a way to choose
                tools that treat creators fairly. The market will do the rest.
              </div>
            </div>

            {/* NOIZY.ai self-certification statement */}
            <div style={{
              padding:"28px 32px",
              background:`linear-gradient(135deg, ${C.goldwarm}0A, ${C.goldwarm}04)`,
              border:`1px solid ${C.goldwarm}33`,
              borderRadius:4,
              display:"flex", gap:24, alignItems:"flex-start",
            }}>
              <CertBadge size={64}/>
              <div>
                <div style={{
                  fontFamily:"DM Sans", fontSize:10, fontWeight:500,
                  color:C.goldwarm, letterSpacing:3, textTransform:"uppercase", marginBottom:8,
                }}>NOIZY.ai — Founding Certified Platform</div>
                <div style={{
                  fontFamily:"Lora", fontSize:15, color:C.ink, lineHeight:1.7, marginBottom:12,
                }}>
                  NOIZY.ai certifies under all eight standards of the Fair Trade AI Audio framework —
                  and publishes its compliance documentation publicly. We built this standard because we
                  needed it ourselves. RSP_001 is the proof of concept. Rob Plowman is the first
                  Fair Trade certified artist. We invite every platform in the industry to join us.
                </div>
                <div style={{fontFamily:"DM Sans", fontSize:11, color:C.mid}}>
                  noizy.ai · noizyvox@noizy.ai
                </div>
              </div>
            </div>
          </div>
        )}

        {/* THE EIGHT STANDARDS */}
        {view==="standards" && (
          <div style={{animation:"rise 0.4s ease"}}>
            <div style={{
              fontFamily:"Playfair Display", fontSize:38, fontWeight:700,
              color:C.ink, marginBottom:8,
            }}>The Eight Standards</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:11, color:C.soft,
              letterSpacing:3, textTransform:"uppercase", marginBottom:12,
            }}>REQUIRED FOR FAIR TRADE AI AUDIO CERTIFICATION</div>
            <div style={{
              fontFamily:"Lora", fontSize:14, fontStyle:"italic",
              color:C.mid, lineHeight:1.7, maxWidth:680, marginBottom:36,
            }}>
              These standards are not aspirational. They are the minimum requirements
              for certification. A platform that meets seven of eight does not receive
              certification. Partial credit does not protect artists. All eight or none.
            </div>

            <div style={{display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(360px,1fr))", gap:16}}>
              {STANDARDS.map((s,i)=>(
                <StandardCard key={i} standard={s} idx={i}/>
              ))}
            </div>

            <div style={{
              marginTop:32, padding:"24px 32px",
              background:C.cream, border:`1px solid ${C.parchmt}`,
              borderRadius:4, textAlign:"center",
            }}>
              <div style={{
                fontFamily:"Playfair Display", fontSize:18, fontWeight:700,
                fontStyle:"italic", color:C.ink, marginBottom:10,
              }}>Every standard above is currently met by NOIZY.ai.</div>
              <div style={{fontFamily:"DM Sans", fontSize:12, color:C.mid, lineHeight:1.7}}>
                This is not a standard we created to exclude competitors. It is a standard
                we created to describe what we already built — and to invite everyone else
                to build it too. The documentation is public. The pathway is open.
                The invitation is genuine.
              </div>
            </div>
          </div>
        )}

        {/* WHO THIS SERVES */}
        {view==="voices" && (
          <div style={{animation:"rise 0.4s ease"}}>
            <div style={{
              fontFamily:"Playfair Display", fontSize:38, fontWeight:700,
              color:C.ink, marginBottom:8,
            }}>Who This Serves</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:11, color:C.soft,
              letterSpacing:3, textTransform:"uppercase", marginBottom:12,
            }}>EVERYONE IN THE CREATIVE AUDIO CHAIN</div>
            <div style={{
              fontFamily:"Lora", fontSize:14, fontStyle:"italic",
              color:C.mid, lineHeight:1.7, maxWidth:680, marginBottom:36,
            }}>
              Fair Trade is not just for artists. It is for everyone who participates
              in a creative economy and wants to know that the tools they use are
              honest about where the value came from.
            </div>

            <div style={{display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(360px,1fr))", gap:16}}>
              {VOICES.map((v,i)=>(
                <VoiceCard key={i} voice={v}/>
              ))}
            </div>
          </div>
        )}

        {/* PATH TO CERTIFICATION */}
        {view==="path" && (
          <div style={{maxWidth:900, animation:"rise 0.4s ease"}}>
            <div style={{
              fontFamily:"Playfair Display", fontSize:38, fontWeight:700,
              color:C.ink, marginBottom:8,
            }}>Path to Certification</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:11, color:C.soft,
              letterSpacing:3, textTransform:"uppercase", marginBottom:12,
            }}>FOR ANY PLATFORM — STARTUP TO ENTERPRISE</div>
            <div style={{
              fontFamily:"Lora", fontSize:14, fontStyle:"italic",
              color:C.mid, lineHeight:1.7, maxWidth:640, marginBottom:40,
            }}>
              We built this pathway because we know that becoming Fair Trade takes time,
              architectural changes, and sometimes hard conversations. The pathway is
              generous because the goal is certification, not gatekeeping.
              We want every platform to make it.
            </div>

            <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:40}}>
              {PLATFORM_PATH.map((step,i)=>(
                <PathStep key={i} step={step}/>
              ))}
            </div>

            {/* The honest acknowledgment section */}
            <div style={{
              padding:"32px 36px",
              background:C.cream, border:`1px solid ${C.parchmt}`,
              borderRadius:4, marginBottom:24,
            }}>
              <div style={{
                fontFamily:"Playfair Display", fontSize:20, fontWeight:700,
                color:C.ink, marginBottom:16,
              }}>A Note to the Platforms We've Analyzed</div>
              <div style={{
                fontFamily:"DM Sans", fontSize:13, color:C.mid, lineHeight:1.8, marginBottom:16,
              }}>
                We have published detailed architectural analyses of ElevenLabs, Suno, Moises,
                and Splice. Those analyses are honest — and some of what we documented is not good
                for creators. We published them not to damage those companies but to make the problem
                visible. Invisible problems do not get solved.
              </div>
              <div style={{
                fontFamily:"Lora", fontSize:14, fontStyle:"italic",
                color:C.earth, lineHeight:1.8, marginBottom:16,
              }}>
                "ElevenLabs: you built something extraordinary. Suno: your music generation is
                genuinely magical. Moises: you have helped millions of musicians learn and create.
                Splice: you gave independent producers a market that didn't exist.
                None of that is diminished by the invitation to do it more fairly."
              </div>
              <div style={{
                fontFamily:"DM Sans", fontSize:13, color:C.mid, lineHeight:1.8,
              }}>
                The door is open. The audit is free. The pathway is twelve months.
                We will help. NOIZY.ai's technical team is available to any platform
                that wants to work toward certification — without charge, without
                judgment, and without public announcement until you're ready.
              </div>
            </div>

            <div style={{
              padding:"20px 28px",
              background:`${C.sage}0F`,
              border:`1px solid ${C.sage}33`,
              borderRadius:4, textAlign:"center",
            }}>
              <div style={{fontFamily:"Lora", fontSize:15, fontStyle:"italic", color:C.earth, marginBottom:8}}>
                To begin the certification process:
              </div>
              <div style={{fontFamily:"DM Sans", fontSize:13, color:C.goldwarm, fontWeight:500}}>
                fairtrade@noizy.ai
              </div>
              <div style={{fontFamily:"DM Sans", fontSize:11, color:C.soft, marginTop:4}}>
                Subject: Fair Trade Certification — [Platform Name]
              </div>
            </div>
          </div>
        )}

        {/* EXAMPLES */}
        {view==="examples" && (
          <div style={{animation:"rise 0.4s ease"}}>
            <div style={{
              fontFamily:"Playfair Display", fontSize:38, fontWeight:700,
              color:C.ink, marginBottom:8,
            }}>What Fair Trade Looks Like</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:11, color:C.soft,
              letterSpacing:3, textTransform:"uppercase", marginBottom:12,
            }}>REAL SCENARIOS. CONCRETE DIFFERENCES.</div>
            <div style={{
              fontFamily:"Lora", fontSize:14, fontStyle:"italic",
              color:C.mid, lineHeight:1.7, maxWidth:680, marginBottom:36,
            }}>
              Fair Trade is not a philosophy. It is a practice. Here is what the difference
              looks like in specific transactions — for artists, for platforms, and for buyers.
            </div>
            {EXAMPLES.map((ex,i)=>(
              <ExampleCard key={i} ex={ex} idx={i}/>
            ))}

            <div style={{
              padding:"28px 32px",
              background:C.cream, border:`1px solid ${C.parchmt}`,
              borderLeft:`4px solid ${C.goldwarm}`,
              borderRadius:4, marginTop:8,
            }}>
              <div style={{
                fontFamily:"Playfair Display", fontSize:16, fontWeight:700,
                color:C.ink, marginBottom:10,
              }}>The Compound Effect</div>
              <div style={{
                fontFamily:"DM Sans", fontSize:13, color:C.mid, lineHeight:1.7,
              }}>
                In each scenario above, Fair Trade is not dramatically more expensive for buyers.
                It is dramatically better for creators. The cost difference to a gaming studio
                choosing a Fair Trade certified voice platform versus an uncertified one is
                negligible. The difference to the voice artist whose work enabled that technology
                is the difference between $0 and a career.
              </div>
            </div>
          </div>
        )}

        {/* PLEDGE */}
        {view==="pledge" && (
          <div style={{maxWidth:760, animation:"rise 0.4s ease"}}>
            <div style={{
              fontFamily:"Playfair Display", fontSize:38, fontWeight:700,
              color:C.ink, marginBottom:8,
            }}>Sign the Pledge</div>
            <div style={{
              fontFamily:"DM Sans", fontSize:11, color:C.soft,
              letterSpacing:3, textTransform:"uppercase", marginBottom:36,
            }}>{pledgeCount.toLocaleString()} SIGNATORIES AND GROWING</div>

            {/* The pledge text */}
            <div style={{
              padding:"32px 36px",
              background:C.cream,
              border:`1px solid ${C.parchmt}`,
              borderTop:`3px solid ${C.goldwarm}`,
              borderRadius:4, marginBottom:28,
            }}>
              <div style={{
                fontFamily:"Playfair Display", fontSize:11, fontWeight:700,
                color:C.goldwarm, letterSpacing:3, textTransform:"uppercase",
                marginBottom:20,
              }}>The Fair Trade AI Audio Pledge</div>
              <div style={{
                fontFamily:"Lora", fontSize:15, color:C.ink,
                lineHeight:2, marginBottom:20,
              }}>
                I believe that human creative work has value that does not diminish
                because a machine can approximate it.
                <br/><br/>
                I believe that the artists who trained the models, built the libraries,
                and created the culture that makes AI audio possible deserve consent,
                credit, and fair compensation.
                <br/><br/>
                I commit to seeking out, supporting, and where possible building
                platforms that meet the Fair Trade AI Audio Standard —
                and to holding others to the same expectation.
                <br/><br/>
                <em style={{color:C.earth}}>
                  This is not anti-AI. This is pro-human.
                  Both can be true at the same time.
                  They must be.
                </em>
              </div>
              <div style={{
                height:1, background:C.parchmt, marginBottom:20,
              }}/>
              <div style={{
                fontFamily:"DM Sans", fontSize:11, color:C.soft,
                fontStyle:"italic",
              }}>
                — Rob Plowman, Founder, NOIZY.ai · Ottawa, Ontario, Canada
              </div>
            </div>

            {/* Sign form */}
            {!signed ? (
              <div style={{
                padding:"28px 32px",
                background:C.cream, border:`1px solid ${C.parchmt}`,
                borderRadius:4,
              }}>
                <div style={{
                  fontFamily:"Playfair Display", fontSize:18, fontWeight:700,
                  color:C.ink, marginBottom:20,
                }}>Add Your Name</div>

                <div style={{marginBottom:16}}>
                  <div style={{
                    fontFamily:"DM Sans", fontSize:10, fontWeight:500,
                    color:C.mid, letterSpacing:2, textTransform:"uppercase", marginBottom:8,
                  }}>Your Name</div>
                  <input
                    value={signName}
                    onChange={e=>setSignName(e.target.value)}
                    placeholder="Your full name"
                    style={{
                      width:"100%", padding:"12px 16px",
                      background:C.warmwht, border:`1px solid ${C.parchmt}`,
                      borderRadius:3, color:C.ink,
                      fontFamily:"Lora", fontSize:14,
                    }}
                  />
                </div>
                <div style={{marginBottom:24}}>
                  <div style={{
                    fontFamily:"DM Sans", fontSize:10, fontWeight:500,
                    color:C.mid, letterSpacing:2, textTransform:"uppercase", marginBottom:8,
                  }}>Your Role</div>
                  <input
                    value={signRole}
                    onChange={e=>setSignRole(e.target.value)}
                    placeholder="Voice actor, composer, producer, developer..."
                    style={{
                      width:"100%", padding:"12px 16px",
                      background:C.warmwht, border:`1px solid ${C.parchmt}`,
                      borderRadius:3, color:C.ink,
                      fontFamily:"DM Sans", fontSize:13, color:C.mid,
                    }}
                  />
                </div>

                <button onClick={handleSign} style={{
                  width:"100%", padding:"16px",
                  background:C.goldwarm,
                  border:"none", borderRadius:3,
                  fontFamily:"Lora", fontSize:15, fontWeight:700,
                  color:C.warmwht, letterSpacing:0.5,
                  transition:"all 0.2s",
                }}>
                  Sign the Fair Trade AI Audio Pledge
                </button>
                <div style={{
                  fontFamily:"DM Sans", fontSize:11, color:C.soft,
                  textAlign:"center", marginTop:12,
                }}>
                  Your name and role will appear in the public signatories list.
                  No email required. No spam. Ever.
                </div>
              </div>
            ) : (
              <div style={{
                padding:"36px 32px",
                background:`${C.sage}0A`,
                border:`1px solid ${C.sage}44`,
                borderRadius:4, textAlign:"center",
                animation:"rise 0.4s ease",
              }}>
                <CertBadge size={64}/>
                <div style={{
                  fontFamily:"Playfair Display", fontSize:24, fontWeight:700,
                  fontStyle:"italic", color:C.ink, marginTop:20, marginBottom:8,
                }}>Thank you, {signName}.</div>
                <div style={{
                  fontFamily:"DM Sans", fontSize:13, color:C.mid, lineHeight:1.7,
                  maxWidth:460, margin:"0 auto",
                }}>
                  You are signatory #{pledgeCount.toLocaleString()}.
                  Every name on this list is a signal to the industry that fair trade
                  in creative AI is not a fringe position. It is a growing majority.
                </div>
                {signRole && (
                  <div style={{
                    marginTop:16, fontFamily:"Lora", fontSize:13,
                    fontStyle:"italic", color:C.soft,
                  }}>
                    {signRole} — committed to fair trade for all.
                  </div>
                )}
              </div>
            )}

            {/* What signing means */}
            <div style={{
              marginTop:24, padding:"20px 24px",
              background:C.cream, border:`1px solid ${C.parchmt}`,
              borderRadius:4,
            }}>
              <div style={{
                fontFamily:"DM Sans", fontSize:10, fontWeight:500,
                color:C.mid, letterSpacing:2, textTransform:"uppercase", marginBottom:12,
              }}>What Signing Does</div>
              {[
                "Adds your name to the public Fair Trade AI Audio signatory list",
                "Signals to platforms that their users expect fair treatment of artists",
                "Gives NOIZY.ai permission to reference the number of signatories in conversations with platforms seeking certification",
                "Costs you nothing and requires no further action — though further action is always welcome",
              ].map((line,i)=>(
                <div key={i} style={{
                  display:"flex", gap:12, padding:"8px 0",
                  borderBottom:i<3?`1px solid ${C.parchmt}`:"none",
                  alignItems:"flex-start",
                }}>
                  <span style={{color:C.goldwarm, flexShrink:0, marginTop:2}}>◯</span>
                  <span style={{fontFamily:"DM Sans", fontSize:12, color:C.mid, lineHeight:1.6}}>{line}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── HARMONY ── */}
        {view==="harmony" && (
          <div style={{animation:"rise 0.4s ease"}}>
            <div style={{background:C.ink,borderRadius:8,padding:"56px 48px",marginBottom:40,textAlign:"center",position:"relative",overflow:"hidden"}}>
              <div style={{position:"absolute",top:0,left:0,right:0,bottom:0,background:`radial-gradient(ellipse at 50% 0%, ${C.goldwarm}18 0%, transparent 65%)`,pointerEvents:"none"}}/>
              <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:4,color:C.goldwarm,textTransform:"uppercase",marginBottom:20}}>A Foundational Principle</div>
              <div style={{fontFamily:"Playfair Display",fontSize:44,fontWeight:700,fontStyle:"italic",color:C.warmwht,lineHeight:1.2,marginBottom:24,maxWidth:720,margin:"0 auto 24px"}}>
                AI is the instrument.<br/>The human is still the musician.
              </div>
              <div style={{fontFamily:"Lora",fontSize:16,color:C.soft,lineHeight:1.8,maxWidth:640,margin:"0 auto"}}>
                Every transformative technology in the history of creative work has been absorbed into the musician's toolkit — the piano, the microphone, the synthesizer, the DAW. AI audio is not different in kind. It is different in scale. The principle that governs the relationship stays the same: the tool serves the creator.
              </div>
            </div>

            <div style={{marginBottom:40}}>
              <div style={{fontFamily:"Playfair Display",fontSize:26,color:C.ink,marginBottom:8}}>The Flywheel</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:28,lineHeight:1.65}}>Ethical AI and thriving artists are not competing outcomes. They are the same outcome, expressed at different points in the same cycle.</div>
              <div style={{display:"flex",flexDirection:"column",gap:0}}>
                {FLYWHEEL_STEPS.map((step,i)=>(
                  <div key={i} style={{display:"flex",alignItems:"stretch",gap:0}}>
                    <div style={{display:"flex",flexDirection:"column",alignItems:"center",width:56,flexShrink:0}}>
                      <div style={{width:40,height:40,borderRadius:"50%",background:i===0||i===4?C.goldwarm:C.parchmt,border:`2px solid ${C.goldwarm}`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"Playfair Display",fontWeight:700,fontSize:14,color:i===0||i===4?C.ink:C.earth,flexShrink:0,zIndex:1}}>{i+1}</div>
                      {i<4&&<div style={{width:2,flex:1,background:`linear-gradient(to bottom,${C.goldwarm}80,${C.parchmt})`,minHeight:24}}/>}
                    </div>
                    <div style={{background:C.cream,border:`1px solid ${C.parchmt}`,borderRadius:6,padding:"20px 24px",marginBottom:i<4?8:0,flex:1}}>
                      <div style={{fontFamily:"DM Sans",fontWeight:700,fontSize:15,color:C.ink,marginBottom:6}}>{step.label}</div>
                      <div style={{fontFamily:"Lora",fontSize:13,color:C.mid,lineHeight:1.65}}>{step.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
              <div style={{marginTop:16,padding:"14px 24px",background:`${C.goldwarm}12`,borderRadius:6,border:`1px solid ${C.goldwarm}44`,textAlign:"center"}}>
                <span style={{fontFamily:"DM Sans",fontSize:12,color:C.earth,fontWeight:500,letterSpacing:1}}>⟳ Each revolution deepens both the model and the artist economy</span>
              </div>
            </div>

            <div style={{marginBottom:40}}>
              <div style={{fontFamily:"Playfair Display",fontSize:26,color:C.ink,marginBottom:8}}>This Is Not Zero Sum</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:28,lineHeight:1.65,maxWidth:680}}>The fear that AI success requires artist failure is understandable — it is what the history of tech extraction would predict. Change the relationship, and the math changes entirely.</div>
              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24}}>
                <div style={{background:C.cream,border:`1px solid ${C.parchmt}`,borderRadius:6,padding:"28px"}}>
                  <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:2,color:C.rose,textTransform:"uppercase",fontWeight:700,marginBottom:14}}>The Extractive Model</div>
                  <div style={{fontFamily:"Lora",fontSize:14,color:C.mid,lineHeight:1.8,marginBottom:16}}>An AI company scrapes your recordings without asking. They train a model that mimics your style. That model generates revenue. None of it reaches you. The better the model gets, the less work comes your way. Your value was consumed to build the thing that replaces you.</div>
                  <div style={{fontFamily:"DM Sans",fontSize:12,color:C.rose,fontStyle:"italic"}}>Artist value → Model value (one-way extraction)</div>
                </div>
                <div style={{background:`linear-gradient(135deg,${C.goldwarm}0F,${C.cream})`,border:`1px solid ${C.goldwarm}44`,borderRadius:6,padding:"28px"}}>
                  <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:2,color:C.goldwarm,textTransform:"uppercase",fontWeight:700,marginBottom:14}}>The Fair Trade Model</div>
                  <div style={{fontFamily:"Lora",fontSize:14,color:C.ink,lineHeight:1.8,marginBottom:16}}>When an AI model gets better because it was trained on your music with your consent, you are a co-creator of that model — not a victim of it. Your contribution is documented, compensated, and attributed. The model's success is structurally connected to your success.</div>
                  <div style={{fontFamily:"DM Sans",fontSize:12,color:C.earth,fontStyle:"italic"}}>Artist value ⟷ Model value (mutual compounding)</div>
                </div>
              </div>
            </div>

            <div style={{marginBottom:40}}>
              <div style={{fontFamily:"Playfair Display",fontSize:26,color:C.ink,marginBottom:8}}>What Harmony Sounds Like</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:28,lineHeight:1.65}}>Collaborations that produce something neither human nor AI could create alone.</div>
              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>
                {HARMONY_PILLARS.map((p,i)=>(
                  <div key={i} style={{background:C.warmwht,border:`1px solid ${C.parchmt}`,borderTop:`3px solid ${p.color}`,borderRadius:6,padding:"28px 24px"}}>
                    <div style={{width:40,height:40,borderRadius:"50%",background:`${p.color}18`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,marginBottom:16}}>{p.icon}</div>
                    <div style={{fontFamily:"Playfair Display",fontSize:17,color:C.ink,marginBottom:10}}>{p.title}</div>
                    <div style={{fontFamily:"Lora",fontSize:13,color:C.mid,lineHeight:1.7}}>{p.body}</div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{background:C.ink,borderRadius:8,padding:"44px 48px",textAlign:"center"}}>
              <div style={{fontFamily:"Playfair Display",fontStyle:"italic",fontSize:20,color:C.warmwht,lineHeight:1.7,maxWidth:680,margin:"0 auto 20px"}}>"I have been a composer, a voice actor, a sound designer. I have also spent years building AI systems. I have never experienced these as competing identities. What Fair Trade AI Audio asks is simply that the entire industry operate from that same premise — that the instrument exists to serve the musician, not to replace them."</div>
              <div style={{fontFamily:"DM Sans",fontSize:11,color:C.goldwarm,letterSpacing:2,textTransform:"uppercase"}}>Rob Plowman — Founder, NOIZY.ai</div>
            </div>
          </div>
        )}

        {/* ── ECOSYSTEM ── */}
        {view==="ecosystem" && (
          <div style={{animation:"rise 0.4s ease"}}>
            <div style={{marginBottom:40}}>
              <div style={{fontFamily:"Playfair Display",fontSize:38,fontWeight:700,color:C.ink,marginBottom:8}}>Every node gains.<br/>No node loses.</div>
              <div style={{fontFamily:"DM Sans",fontSize:11,color:C.soft,letterSpacing:3,textTransform:"uppercase",marginBottom:12}}>THE NOIZY ECOSYSTEM</div>
              <div style={{fontFamily:"Lora",fontSize:15,fontStyle:"italic",color:C.mid,lineHeight:1.75,maxWidth:680}}>The creative economy has always been an ecosystem, not a hierarchy. Every participant's success is entangled with every other participant's success. Fair Trade AI Audio makes that entanglement explicit — and builds the infrastructure to honor it.</div>
            </div>

            <div style={{marginBottom:48}}>
              <div style={{fontFamily:"Playfair Display",fontSize:24,color:C.ink,marginBottom:28}}>Ecosystem Map</div>
              <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(320px,1fr))",gap:20}}>
                {ECOSYSTEM_NODES.map((node,i)=>(
                  <div key={i} style={{background:C.warmwht,border:`1px solid ${C.parchmt}`,borderTop:`3px solid ${node.color}`,borderRadius:6,padding:"24px 20px"}}>
                    <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:16}}>
                      <div style={{width:40,height:40,borderRadius:"50%",background:`${node.color}20`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"DM Sans",fontWeight:800,fontSize:12,color:node.color,flexShrink:0}}>{node.initials}</div>
                      <div style={{fontFamily:"DM Sans",fontWeight:700,fontSize:14,color:C.ink}}>{node.role}</div>
                    </div>
                    <div style={{marginBottom:12}}>
                      <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:1.5,color:C.earth,textTransform:"uppercase",fontWeight:700,marginBottom:6}}>Gives</div>
                      <div style={{fontFamily:"Lora",fontSize:12,color:C.mid,lineHeight:1.65}}>{node.gives}</div>
                    </div>
                    <div style={{borderTop:`1px solid ${C.parchmt}`,paddingTop:12}}>
                      <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:1.5,color:node.color,textTransform:"uppercase",fontWeight:700,marginBottom:6}}>Receives</div>
                      <div style={{fontFamily:"Lora",fontSize:12,color:C.ink,lineHeight:1.65}}>{node.receives}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{marginBottom:48}}>
              <div style={{fontFamily:"Playfair Display",fontSize:24,color:C.ink,marginBottom:8}}>The Compounding Effect</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:28,lineHeight:1.65}}>Each new Fair Trade certified platform makes the entire network more valuable. The value compounds faster at the edges than at the center.</div>
              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:20}}>
                {GROWTH_PHASES.map((phase,i)=>(
                  <div key={i} style={{background:i===2?`linear-gradient(135deg,${C.goldwarm}12,${C.cream})`:C.cream,border:`1px solid ${i===2?C.goldwarm+"44":C.parchmt}`,borderRadius:6,padding:"28px 24px"}}>
                    <div style={{display:"inline-block",padding:"4px 12px",background:i===2?C.goldwarm:i===1?C.earth:C.mid,borderRadius:20,fontFamily:"DM Sans",fontSize:11,fontWeight:700,color:i===2?C.ink:C.warmwht,letterSpacing:1,marginBottom:16}}>Phase {i+1}: {phase.phase}</div>
                    <div style={{fontFamily:"Playfair Display",fontSize:17,color:C.ink,marginBottom:12,lineHeight:1.35}}>{phase.title}</div>
                    <div style={{fontFamily:"Lora",fontSize:13,color:C.mid,lineHeight:1.7,marginBottom:16}}>{phase.desc}</div>
                    <div style={{borderTop:`1px solid ${C.parchmt}`,paddingTop:14}}>
                      <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:1,color:C.earth,textTransform:"uppercase",fontWeight:700,marginBottom:6}}>Milestone Marker</div>
                      <div style={{fontFamily:"Lora",fontStyle:"italic",fontSize:12,color:C.ink,lineHeight:1.6}}>{phase.milestone}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{marginBottom:48}}>
              <div style={{fontFamily:"Playfair Display",fontSize:24,color:C.ink,marginBottom:28}}>The NOIZY Product Suite</div>
              <div style={{display:"flex",flexDirection:"column",gap:12}}>
                {NOIZY_PRODUCTS.map((product,i)=>(
                  <div key={i} style={{display:"flex",alignItems:"flex-start",gap:20,background:C.warmwht,border:`1px solid ${C.parchmt}`,borderLeft:`4px solid ${product.color}`,borderRadius:6,padding:"22px 28px"}}>
                    <div style={{flex:1}}>
                      <div style={{display:"flex",alignItems:"baseline",gap:12,marginBottom:6,flexWrap:"wrap"}}>
                        <div style={{fontFamily:"DM Sans",fontWeight:800,fontSize:16,color:C.ink}}>{product.name}</div>
                        <div style={{fontFamily:"Lora",fontStyle:"italic",fontSize:13,color:C.mid}}>{product.tagline}</div>
                      </div>
                      <div style={{fontFamily:"Lora",fontSize:13,color:C.mid,lineHeight:1.65}}>
                        <span style={{fontFamily:"DM Sans",fontSize:10,fontWeight:700,letterSpacing:1,color:product.color,textTransform:"uppercase",marginRight:6}}>Serves:</span>{product.serves}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{background:C.ink,borderRadius:8,padding:"44px 48px",textAlign:"center"}}>
              <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:3,color:C.goldwarm,textTransform:"uppercase",marginBottom:16}}>A Living Standard</div>
              <div style={{fontFamily:"Playfair Display",fontSize:24,color:C.warmwht,marginBottom:20,lineHeight:1.3}}>The standard itself is part of the ecosystem</div>
              <div style={{fontFamily:"Lora",fontSize:15,color:C.soft,lineHeight:1.8,maxWidth:640,margin:"0 auto"}}>Fair Trade AI Audio is not a document written by a committee and handed down to artists. It is a living standard that evolves with the technology and with the creative community's direct input. Artists, voice actors, developers, and platforms all have mechanisms to propose amendments. The standard is owned by the ecosystem it serves.</div>
            </div>
          </div>
        )}

        {/* ── VISION ── */}
        {view==="vision" && (
          <div style={{animation:"rise 0.4s ease"}}>
            <div style={{background:C.ink,borderRadius:8,padding:"64px 48px",marginBottom:48,textAlign:"center",position:"relative",overflow:"hidden"}}>
              <div style={{position:"absolute",top:0,left:0,right:0,bottom:0,background:`radial-gradient(ellipse at 30% 50%,${C.goldwarm}14 0%,transparent 55%),radial-gradient(ellipse at 70% 50%,${C.rose}0A 0%,transparent 55%)`,pointerEvents:"none"}}/>
              <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:3,color:C.goldwarm,textTransform:"uppercase",marginBottom:24}}>The Long Arc</div>
              <div style={{fontFamily:"Playfair Display",fontSize:28,fontStyle:"italic",color:C.warmwht,lineHeight:1.65,maxWidth:760,margin:"0 auto 28px"}}>"In 2044, every AI model will carry a training provenance record the way every food product carries an ingredients list. We are building the infrastructure that makes that normal."</div>
              <div style={{fontFamily:"DM Sans",fontSize:11,color:C.goldwarm,letterSpacing:2,textTransform:"uppercase"}}>Rob Plowman — NOIZY.ai</div>
            </div>

            <div style={{marginBottom:56}}>
              <div style={{fontFamily:"Playfair Display",fontSize:26,color:C.ink,marginBottom:8}}>Timeline of Change</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:36,lineHeight:1.65}}>These milestones are not predictions. They are commitments — the specific waypoints NOIZY is building toward and will measure itself against.</div>
              <div style={{display:"flex",flexDirection:"column",gap:0}}>
                {VISION_TIMELINE.map((item,i)=>{
                  const sc = item.status==="done"?C.sage:item.status==="near"?C.goldwarm:C.mid;
                  const sl = item.status==="done"?"In Progress":item.status==="near"?"Near Horizon":"Long Horizon";
                  return (
                    <div key={i} style={{display:"flex",gap:0,alignItems:"stretch"}}>
                      <div style={{width:96,flexShrink:0,display:"flex",flexDirection:"column",alignItems:"flex-end",paddingRight:24,paddingTop:4}}>
                        <span style={{fontFamily:"Playfair Display",fontSize:24,fontWeight:700,color:sc,lineHeight:1}}>{item.year}</span>
                      </div>
                      <div style={{display:"flex",flexDirection:"column",alignItems:"center",width:24,flexShrink:0}}>
                        <div style={{width:14,height:14,borderRadius:"50%",background:sc,border:`3px solid ${C.warmwht}`,boxShadow:`0 0 0 2px ${sc}`,flexShrink:0,marginTop:4}}/>
                        {i<4&&<div style={{width:2,flex:1,background:`linear-gradient(to bottom,${sc}80,${C.parchmt})`,minHeight:32}}/>}
                      </div>
                      <div style={{paddingLeft:24,paddingBottom:i<4?36:0,flex:1}}>
                        <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:10,flexWrap:"wrap"}}>
                          <div style={{fontFamily:"DM Sans",fontWeight:700,fontSize:17,color:C.ink}}>{item.title}</div>
                          <span style={{padding:"2px 10px",background:`${sc}20`,border:`1px solid ${sc}50`,borderRadius:20,fontFamily:"DM Sans",fontSize:11,color:sc,fontWeight:600,letterSpacing:0.5}}>{sl}</span>
                        </div>
                        <div style={{fontFamily:"Lora",fontSize:14,color:C.mid,lineHeight:1.75,maxWidth:600}}>{item.desc}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <div style={{marginBottom:56}}>
              <div style={{fontFamily:"Playfair Display",fontSize:26,color:C.ink,marginBottom:8}}>Letters to the Future</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:32,lineHeight:1.65}}>The people who will benefit most from the work happening now are not yet in the conversation. This section is written for them.</div>
              <div style={{display:"flex",flexDirection:"column",gap:20}}>
                {LETTERS.map((letter,i)=>(
                  <div key={i} style={{background:C.warmwht,border:`1px solid ${C.parchmt}`,borderTop:`3px solid ${C.goldwarm}`,borderRadius:6,padding:"32px 36px",position:"relative",overflow:"hidden"}}>
                    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:16,flexWrap:"wrap",gap:8}}>
                      <div>
                        <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:2,color:C.goldwarm,textTransform:"uppercase",fontWeight:700,marginBottom:4}}>A Letter To</div>
                        <div style={{fontFamily:"Playfair Display",fontStyle:"italic",fontSize:18,color:C.ink}}>{letter.to}</div>
                      </div>
                      <span style={{fontFamily:"Playfair Display",fontSize:32,fontWeight:700,color:C.parchmt,lineHeight:1}}>{letter.year}</span>
                    </div>
                    <div style={{fontFamily:"Lora",fontSize:14,color:C.mid,lineHeight:1.85}}>{letter.body}</div>
                  </div>
                ))}
              </div>
            </div>

            <div style={{marginBottom:48}}>
              <div style={{background:`linear-gradient(135deg,${C.ink},#1a1510)`,borderRadius:8,padding:"48px 48px",position:"relative",overflow:"hidden"}}>
                <div style={{position:"absolute",top:0,right:0,width:280,height:280,background:`radial-gradient(circle,${C.goldwarm}0E,transparent 65%)`,pointerEvents:"none"}}/>
                <div style={{fontFamily:"DM Sans",fontSize:10,letterSpacing:3,color:C.goldwarm,textTransform:"uppercase",marginBottom:16}}>Why NOIZY.ai Exists</div>
                <div style={{fontFamily:"Playfair Display",fontSize:24,color:C.warmwht,marginBottom:28,lineHeight:1.3,maxWidth:600}}>The view from the intersection</div>
                <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:32}}>
                  <div>
                    <div style={{fontFamily:"Lora",fontSize:14,color:C.soft,lineHeight:1.8,marginBottom:20}}>I am a composer. I have written music for film, television, and advertising. I understand the economics of licensing, the anxiety of sync placement, the particular vulnerability of watching your work get close to a placement and then not get it.</div>
                    <div style={{fontFamily:"Lora",fontSize:14,color:C.soft,lineHeight:1.8}}>I am a voice actor. I know what it means to have your voice be your instrument — the thing you have spent years developing, the asset that is entirely yours and entirely vulnerable to being replicated without your permission.</div>
                  </div>
                  <div>
                    <div style={{fontFamily:"Lora",fontSize:14,color:C.soft,lineHeight:1.8,marginBottom:20}}>I am a sound designer and a technologist. I have built AI systems. I understand how training pipelines work, where the consent gaps are, and what it would take to close them. I am not standing outside the machine describing it — I built versions of it.</div>
                    <div style={{fontFamily:"Lora",fontStyle:"italic",fontSize:14,color:C.goldlt,lineHeight:1.8}}>NOIZY.ai exists because someone who has sat in all four chairs had to build the thing that makes those chairs face each other rather than away from each other.</div>
                  </div>
                </div>
                <div style={{marginTop:28,textAlign:"right"}}>
                  <div style={{fontFamily:"DM Sans",fontSize:11,color:C.goldwarm,letterSpacing:2,textTransform:"uppercase"}}>Rob Plowman — Composer, Voice Actor, Sound Designer, Technologist</div>
                </div>
              </div>
            </div>

            <div>
              <div style={{fontFamily:"Playfair Display",fontSize:26,color:C.ink,marginBottom:8}}>Join the Next Chapter</div>
              <div style={{fontFamily:"Lora",fontSize:14,fontStyle:"italic",color:C.mid,marginBottom:32,lineHeight:1.65}}>The standard grows by action, not by agreement.</div>
              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>
                {[
                  {title:"Sign the Pledge",desc:"Add your name publicly. Signal that you hold these principles as an artist, a platform, or a developer.",action:"Sign the Pledge",color:C.goldwarm,tab:"pledge"},
                  {title:"Apply for Certification",desc:"If you operate a platform or AI service that works with audio, begin the certification process. The audit is thorough. The credential is real.",action:"Start Application",color:C.sage,tab:"path"},
                  {title:"Use Fair Trade Tools",desc:"GABRIEL, NOIZY Guild, NOIZY DreamChamber, and the NOIZY Sample Marketplace are all built on Fair Trade infrastructure. Using them is a form of participation.",action:"Explore NOIZY.ai",color:C.earth,tab:null},
                  {title:"Spread the Standard",desc:"Share this page with musicians, voice actors, sound designers, developers, and supervisors in your network. The standard grows by word of mouth before it grows by legislation.",action:"Share This Page",color:C.rose,tab:null},
                ].map((cta,i)=>(
                  <div key={i} style={{background:C.warmwht,border:`1px solid ${C.parchmt}`,borderRadius:6,padding:"28px 24px",display:"flex",flexDirection:"column",justifyContent:"space-between"}}>
                    <div>
                      <div style={{width:10,height:10,borderRadius:"50%",background:cta.color,marginBottom:16}}/>
                      <div style={{fontFamily:"Playfair Display",fontSize:18,color:C.ink,marginBottom:10}}>{cta.title}</div>
                      <div style={{fontFamily:"Lora",fontSize:13,color:C.mid,lineHeight:1.7,marginBottom:24}}>{cta.desc}</div>
                    </div>
                    <button onClick={()=>cta.tab?setView(cta.tab):null} style={{background:cta.color,color:cta.color===C.goldwarm?C.ink:C.warmwht,border:"none",borderRadius:4,padding:"12px 20px",fontFamily:"DM Sans",fontWeight:700,fontSize:13,cursor:"pointer",letterSpacing:0.5,alignSelf:"flex-start"}}>{cta.action}</button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

      </div>

      {/* ── FOOTER ───────────────────────────────────────────── */}
      <div style={{
        padding:"36px 40px",
        background:C.cream,
        borderTop:`1px solid ${C.parchmt}`,
      }}>
        <div style={{
          display:"grid", gridTemplateColumns:"1fr auto 1fr",
          alignItems:"center", gap:40, maxWidth:1200, margin:"0 auto",
        }}>
          <div>
            <div style={{
              fontFamily:"Playfair Display", fontSize:14, fontWeight:700,
              color:C.ink, marginBottom:6,
            }}>Fair Trade AI Audio</div>
            <div style={{fontFamily:"DM Sans", fontSize:11, color:C.soft, lineHeight:1.6}}>
              An open standard for human-centred creative AI.<br/>
              Founded and maintained by NOIZY.ai.<br/>
              Free to adopt. Permanent when achieved.
            </div>
          </div>
          <CertBadge size={56}/>
          <div style={{textAlign:"right"}}>
            <div style={{fontFamily:"Lora", fontSize:16, fontStyle:"italic", color:C.goldwarm, marginBottom:6}}>
              "Fair trade for all."
            </div>
            <div style={{fontFamily:"DM Sans", fontSize:11, color:C.soft}}>
              Rob Plowman · Founder, NOIZY.ai<br/>
              Ottawa, Ontario, Canada<br/>
              fairtrade@noizy.ai · noizy.ai
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
