#!/bin/bash

echo "🔑 Direct OAuth Token Creation"
echo ""
echo "Go to: https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "Look for 'Wrangler Tokens' section (not API Tokens)"
echo "You might see existing tokens there from previous logins"
echo ""
echo "OR create new token:"
echo "1. Create Token → Edit Cloudflare Workers template"
echo "2. Account Resources → Include → Your Account"
echo "3. Zone Resources → Include → All zones"
echo "4. Continue → Create Token"
echo "5. Copy the token"
echo ""
echo "Then run:"
echo "export CLOUDFLARE_API_TOKEN='your-token'"
echo "wrangler whoami"
echo ""
echo "Once working, Cascade will unblock automatically"
