name = "noizy-coming-soon"
main = "worker.js"
compatibility_date = "2024-09-02"
account_id = "5f36aa9795348ea681d0b21910dfc82a"

[triggers]
crons = []

# To deploy: wrangler deploy
# To preview locally: wrangler dev
